movies:
  base:
    url: https://movie-app-rjl.cfapps.io/
songs:
  base:
    url: https://song-app-rjl.cfapps.io/
spring:
  application:
    name: discovery-app-rjl
  cloud:
    services:
      registrationMethod: route
